name: Westcoast Audio Video Gallery
description: Highend Audio Video and Home Theater Store
google_analytics: UA-10255320-2
url: http://westcoastavgallery.ca
baseurl: ""
redirects: yes
defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true # automatically set is_post=true for all posts

collections:
  products:
    output: true
    permalink: /:collection/:title
  brands:
    output: true
    permalink: /:collection/:title
  product-categories:
    output: true
    permalink: /:collection/:title


markdown: redcarpet
highlighter: rouge
permalink: /:title/

version: v1.1.0

sass:
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-sitemap

# Exclude these files from your production _site
exclude:
    - webpack
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

# Build settings
markdown: kramdown


