brands:
  - name: Denon
    slug: denon
  - name: Martin Logan
    slug: martin-logan
  - name: AC Infinity
    slug: ac-infinity
  - name: Anthem
    slug: anthem
  - name: AudioQuest
    slug: audioquest
  - name: BDI
    slug: bdi
  - name: Bryston
    slug: bryston
  - name: Cambridge Audio
    slug: cambridge-audio
  - name: Crown
    slug: crown
  - name: Cyrus
    slug: cyrus
  - name: Dayton Audio
    slug: dayton-audio
  - name: Elac
    slug: elac
  - name: Epson
    slug: epson
  - name: EPV
    slug: epv
  - name: Focal
    slug: focal
  - name: Grado
    slug: grado
  - name: Kanto
    slug: kanto
  - name: Martin Logan
    slug: martin-logan
