backend:
  name: github
  repo: westcoastavgallery/westcoastavgallery.github.io
  branch: master
  base_url: https://westcoast-oath-provider.herokuapp.com

media_folder: "img/uploads"

collections: # A list of collections the CMS should be able to edit 
  - name: "speaker" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Speaker" # Used in the UI, ie.: "New Post"
    folder: "_speakers" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Thumbnail", name: thumbnail, widget: image, class: "thumb"}
      - name: images
        label: "More Images"
        widget: list
        fields:
          - {label: "Thumbnail", name: thumbnail, widget: image, class: "thumb"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Short Description", name: "short", widget: "string"}
      - {label: "Sku", name: "sku", widget: "string"}
      - {label: "Brand", name: "brand", widget: "string"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}