backend:
  name: github
  repo: westcoastavgallery/westcoastavgallery.github.io
  branch: master
  base_url: http://api.westcoastavgallery.ca:7777

media_folder: "img/uploads"

collections: # A list of collections the CMS should be able to edit 
  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Products" # Used in the UI, ie.: "New Post"
    folder: "_products" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Show", name: show, widget: boolean}
#      - {label: "Thumbnail", name: thumbnail, widget: image, class: "thumb"}
      - name: images
        label: "More Images"
        widget: list
        fields:
          - {label: "Thumbnail", name: thumbnail, widget: image, class: "thumb"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Short Description", name: "short", widget: "string"}
      - {label: "Sku", name: "sku", widget: "string"}
      - {label: "Brand", name: "brand", widget: "relation", collection: "brands", searchFields: ["name","slug"], valueField: "name"}
      - {label: "Category", name: "category", widget: "relation", collection: "product-categories", searchFields: ["name","slug"], valueField: "name"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Shipping Price", name: "shipping", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "brands" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Brands" # Used in the UI, ie.: "New Post"
    folder: "_brands" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Show", name: show, widget: boolean}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
  - name: "product-categories" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Product Category" # Used in the UI, ie.: "New Post"
    folder: "_product-categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Show", name: show, widget: boolean}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}


  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "product-categories"
        label: "Product Categories"
        file: "_data/product-categories.yml"
        description: "Product Categories"
        fields:
          - name: categories
            label: Categories
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Slug", name: "slug", widget: "string"}
