backend:
  name: github
  repo: westcoastavgallery/westcoastavgallery.github.io
  branch: master
  base_url:  http://localhost:7777

media_folder: "img/uploads"

collections: # A list of collections the CMS should be able to edit 
  - name: "products" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Products" # Used in the UI, ie.: "New Post"
    folder: "_products" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Thumbnail", name: thumbnail, widget: image, class: "thumb"}
      - name: images
        label: "More Images"
        widget: list
        fields:
          - {label: "Thumbnail", name: thumbnail, widget: image, class: "thumb"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Short Description", name: "short", widget: "string"}
      - {label: "Sku", name: "sku", widget: "string"}
      - name: brand
        label: Brand
        widget: relation
        collection: brands
        searchFields: [name]
        valueField: slug
      - name: categories
        label: Categories
        widget: relation
        collection: product-categories
        searchFields: [name]
        valueField: slug
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "product-categories"
        label: "Product Categories"
        file: "_data/product-categories.yml"
        description: "Product Categories"
        fields:
          - name: categories
            label: Categories
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Slug", name: "slug", widget: "string"}
